#ifndef _H_DEMO_TEST_CONFIG_H_
#define _H_DEMO_TEST_CONFIG_H_

#define DEMO_TEST_MODEL_BTC550DP_ULTRA      1
#define DEMO_TEST_MODEL_BTC500DP_PRO        2
#define DEMO_TEST_MODEL_BTC500DP_5GEN_PRO   3
#define DEMO_TEST_MODEL_BTC500DP_7GEN_PRO   4

#define DEMO_TEST_PROTO_ULTRA_LIKE          1
#define DEMO_TEST_PROTO_5GEN                2

#ifndef DEMO_TEST_MODEL
#define DEMO_TEST_MODEL DEMO_TEST_MODEL_BTC500DP_PRO
#endif

#if (DEMO_TEST_MODEL == DEMO_TEST_MODEL_BTC550DP_ULTRA)
#define DEMO_TEST_MODEL_NAME            "BTC550DP Ultra"
#define DEMO_TEST_DEVICE_TYPE           0x0003u
#define DEMO_TEST_SUPPORT_MODE          1
#define DEMO_TEST_SUPPORT_T2T4          1
#define DEMO_TEST_SUPPORT_CURRENT       1
#define DEMO_TEST_SUPPORT_POSTGAS       1
#define DEMO_TEST_SUPPORT_ARC           1
#define DEMO_TEST_SUPPORT_UNIT          1
#define DEMO_TEST_SUPPORT_ALARM         1
#define DEMO_TEST_SUPPORT_VOLTAGE       1
#define DEMO_TEST_SUPPORT_BAR           1
#define DEMO_TEST_PROTOCOL_VARIANT      DEMO_TEST_PROTO_ULTRA_LIKE
#define DEMO_TEST_MODE_MIN              0u
#define DEMO_TEST_MODE_MAX              3u
#define DEMO_TEST_CURRENT_MIN           15u
#define DEMO_TEST_CURRENT_MAX_120V_MODE_0  40u
#define DEMO_TEST_CURRENT_MAX_120V_MODE_1  30u
#define DEMO_TEST_CURRENT_MAX_120V_MODE_2  30u
#define DEMO_TEST_CURRENT_MAX_120V_MODE_3  40u
#define DEMO_TEST_CURRENT_MAX_240V_MODE_0  55u
#define DEMO_TEST_CURRENT_MAX_240V_MODE_1  30u
#define DEMO_TEST_CURRENT_MAX_240V_MODE_2  30u
#define DEMO_TEST_CURRENT_MAX_240V_MODE_3  55u

#elif (DEMO_TEST_MODEL == DEMO_TEST_MODEL_BTC500DP_PRO)
#define DEMO_TEST_MODEL_NAME            "BTC500DP PRO"
#define DEMO_TEST_DEVICE_TYPE           0x0002u
#define DEMO_TEST_SUPPORT_MODE          1
#define DEMO_TEST_SUPPORT_T2T4          1
#define DEMO_TEST_SUPPORT_CURRENT       1
#define DEMO_TEST_SUPPORT_POSTGAS       1
#define DEMO_TEST_SUPPORT_ARC           1
#define DEMO_TEST_SUPPORT_UNIT          1
#define DEMO_TEST_SUPPORT_ALARM         1
#define DEMO_TEST_SUPPORT_VOLTAGE       1
#define DEMO_TEST_SUPPORT_BAR           1
#define DEMO_TEST_PROTOCOL_VARIANT      DEMO_TEST_PROTO_ULTRA_LIKE
#define DEMO_TEST_MODE_MIN              0u
#define DEMO_TEST_MODE_MAX              2u
#define DEMO_TEST_CURRENT_MIN           15u
#define DEMO_TEST_CURRENT_MAX_120V_MODE_0  35u
#define DEMO_TEST_CURRENT_MAX_120V_MODE_1  30u
#define DEMO_TEST_CURRENT_MAX_120V_MODE_2  30u
#define DEMO_TEST_CURRENT_MAX_120V_MODE_3  30u
#define DEMO_TEST_CURRENT_MAX_240V_MODE_0  50u
#define DEMO_TEST_CURRENT_MAX_240V_MODE_1  30u
#define DEMO_TEST_CURRENT_MAX_240V_MODE_2  30u
#define DEMO_TEST_CURRENT_MAX_240V_MODE_3  30u

#elif (DEMO_TEST_MODEL == DEMO_TEST_MODEL_BTC500DP_5GEN_PRO)
#define DEMO_TEST_MODEL_NAME            "BTC500DP 5GEN PRO"
#define DEMO_TEST_DEVICE_TYPE           0x0005u
#define DEMO_TEST_SUPPORT_MODE          0
#define DEMO_TEST_SUPPORT_T2T4          1
#define DEMO_TEST_SUPPORT_CURRENT       1
#define DEMO_TEST_SUPPORT_POSTGAS       1
#define DEMO_TEST_SUPPORT_ARC           0
#define DEMO_TEST_SUPPORT_UNIT          1
#define DEMO_TEST_SUPPORT_ALARM         1
#define DEMO_TEST_SUPPORT_VOLTAGE       1
#define DEMO_TEST_SUPPORT_BAR           0
#define DEMO_TEST_PROTOCOL_VARIANT      DEMO_TEST_PROTO_5GEN
#define DEMO_TEST_MODE_MIN              0u
#define DEMO_TEST_MODE_MAX              0u
#define DEMO_TEST_CURRENT_MIN           15u
#define DEMO_TEST_CURRENT_MAX_120V_MODE_0  35u
#define DEMO_TEST_CURRENT_MAX_120V_MODE_1  35u
#define DEMO_TEST_CURRENT_MAX_120V_MODE_2  35u
#define DEMO_TEST_CURRENT_MAX_120V_MODE_3  35u
#define DEMO_TEST_CURRENT_MAX_240V_MODE_0  50u
#define DEMO_TEST_CURRENT_MAX_240V_MODE_1  50u
#define DEMO_TEST_CURRENT_MAX_240V_MODE_2  50u
#define DEMO_TEST_CURRENT_MAX_240V_MODE_3  50u

#elif (DEMO_TEST_MODEL == DEMO_TEST_MODEL_BTC500DP_7GEN_PRO)
#define DEMO_TEST_MODEL_NAME            "BTC500DP 7GEN PRO"
#define DEMO_TEST_DEVICE_TYPE           0x0004u
#define DEMO_TEST_SUPPORT_MODE          1
#define DEMO_TEST_SUPPORT_T2T4          1
#define DEMO_TEST_SUPPORT_CURRENT       1
#define DEMO_TEST_SUPPORT_POSTGAS       1
#define DEMO_TEST_SUPPORT_ARC           1
#define DEMO_TEST_SUPPORT_UNIT          1
#define DEMO_TEST_SUPPORT_ALARM         1
#define DEMO_TEST_SUPPORT_VOLTAGE       1
#define DEMO_TEST_SUPPORT_BAR           1
#define DEMO_TEST_PROTOCOL_VARIANT      DEMO_TEST_PROTO_ULTRA_LIKE
#define DEMO_TEST_MODE_MIN              0u
#define DEMO_TEST_MODE_MAX              2u
#define DEMO_TEST_CURRENT_MIN           15u
#define DEMO_TEST_CURRENT_MAX_120V_MODE_0  35u
#define DEMO_TEST_CURRENT_MAX_120V_MODE_1  30u
#define DEMO_TEST_CURRENT_MAX_120V_MODE_2  30u
#define DEMO_TEST_CURRENT_MAX_120V_MODE_3  30u
#define DEMO_TEST_CURRENT_MAX_240V_MODE_0  50u
#define DEMO_TEST_CURRENT_MAX_240V_MODE_1  30u
#define DEMO_TEST_CURRENT_MAX_240V_MODE_2  30u
#define DEMO_TEST_CURRENT_MAX_240V_MODE_3  30u

#else
#error "Unsupported DEMO_TEST_MODEL"
#endif

#define DEMO_TEST_T2T4_MIN              0u
#define DEMO_TEST_T2T4_MAX              1u
#define DEMO_TEST_POSTGAS_MIN           3u
#define DEMO_TEST_POSTGAS_MAX           15u
#define DEMO_TEST_ARC_MIN               3u
#define DEMO_TEST_ARC_MAX               15u
#define DEMO_TEST_UNIT_MIN              0u
#define DEMO_TEST_UNIT_MAX              (DEMO_TEST_SUPPORT_BAR ? 2u : 1u)
#define DEMO_TEST_ALARM_VALUE           0u
#define DEMO_TEST_ALARM_MIN             0u
#define DEMO_TEST_ALARM_MAX             2u
#define DEMO_TEST_VOLTAGE_MIN           0u
#define DEMO_TEST_VOLTAGE_MAX           1u

#endif /* _H_DEMO_TEST_CONFIG_H_ */
